# -*- coding: utf-8 -*-
"""thyroid.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qR2yKJi68dTtMNzxj5pHJNV5kNqMeyn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier
import shap

df = pd.read_csv("/content/Thyroid_Diff.csv.xls")

print("Original Shape:", df.shape)
print(df.head())

print(df['Recurred'].value_counts())

for col in df.select_dtypes(include=['int64', 'float64']).columns:
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

df.drop_duplicates(inplace=True)

df['Recurred'] = df['Recurred'].map({'No': 0, 'Yes': 1})

df = pd.get_dummies(df, drop_first=True)

df = df.astype(int)

print("Cleaned Shape:", df.shape)
print(df.info())

df.to_csv("cleaned_thyroid.csv", index=False)

X = df.drop('Recurred', axis=1)
y = df['Recurred']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(n_estimators=100, random_state=42)
dt = DecisionTreeClassifier(random_state=42)
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')

lr.fit(X_train, y_train)
rf.fit(X_train, y_train)
dt.fit(X_train, y_train)
xgb.fit(X_train, y_train)

models = {'Logistic': lr, 'Random Forest': rf, 'Decision Tree': dt, 'XGBoost': xgb}

for name, model in models.items():
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)
    print(f"{name} Accuracy: {acc}")

importances = rf.feature_importances_
features = X.columns

feat_imp = pd.Series(importances, index=features).sort_values(ascending=False)

print("\nTop Features:")
print(feat_imp.head(10))

importances = rf.feature_importances_
features = X.columns

feat_imp = pd.Series(importances, index=features).sort_values(ascending=False)

print("\nTop Features:")
print(feat_imp.head(10))

def predict_risk(model, input_data):
    return model.predict_proba([input_data])[0][1]

sample = X.iloc[0].values

risk = predict_risk(xgb, sample)
print("\nPredicted Recurrence Risk:", risk)

modified = sample.copy()

# Example change (Age)
modified[0] = modified[0] - 5

risk_original = predict_risk(xgb, sample)
risk_modified = predict_risk(xgb, modified)

print("\nOriginal Risk:", risk_original)
print("Modified Risk:", risk_modified)

plt.bar(['Original', 'Modified'], [risk_original, risk_modified])
plt.title("Risk Comparison")
plt.show()

import matplotlib.pyplot as plt

modified = sample.copy()

feature_list = list(X.columns)

# Try a strong feature
idx = feature_list.index('N_N1b')   # lymph node spread (important)

# TOGGLE value
modified[idx] = 1 - modified[idx]

# Predict
risk_original = predict_risk(xgb, sample)
risk_modified = predict_risk(xgb, modified)

print("Original Risk:", risk_original)
print("Modified Risk:", risk_modified)

# Plot
plt.figure()
plt.bar(['Original', 'Modified'], [risk_original, risk_modified])
plt.title("Risk Comparison (After Changing N_N1b)")
plt.xlabel("Scenario")
plt.ylabel("Risk Probability")
plt.show()

ages = range(30, 80, 5)
risks = []

for age in ages:
    temp = sample.copy()
    temp[0] = age
    risks.append(predict_risk(xgb, temp))

plt.plot(ages, risks, marker='o')
plt.xlabel("Age")
plt.ylabel("Risk")
plt.title("Age vs Risk")
plt.show()

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

best_risk = risk_original
best_feature = None

for i in range(len(sample)):
    temp = sample.copy()
    temp[i] = 0

    new_risk = predict_risk(xgb, temp)

    if new_risk < best_risk:
        best_risk = new_risk
        best_feature = X.columns[i]

print("\nBest Feature to Change:", best_feature)
print("New Risk:", best_risk)

from scipy.stats import ttest_ind

group1 = df[df['Smoking_Yes'] == 1]['Recurred']
group2 = df[df['Smoking_Yes'] == 0]['Recurred']

t_stat, p_val = ttest_ind(group1, group2)

print("P-value:", p_val)

import seaborn as sns

# Top 10 features only (Darker colors indicate stronger while lighter color indicates weaker relationship)
top_features = df.corr()['Recurred'].abs().sort_values(ascending=False).head(10).index

sns.heatmap(df[top_features].corr(), annot=True, cmap='coolwarm')
plt.show()

import pickle

with open('thyroid.pkl','wb') as f:
    pickle.dump(models,f)

