# -*- coding: utf-8 -*-
"""training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMfyH07WWpp197OVzdwxujtPbJc2ygp3
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
import pickle

df = pd.read_csv("/content/Thyroid_Diff.csv.xls")

# Select only required columns
features = ["Age", "Gender", "Smoking", "Adenopathy", "Focality", "Stage"]
X = df[features]
y = df["Recurred"]

# Preprocessing
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown='ignore'),
     ["Gender", "Smoking", "Adenopathy", "Focality", "Stage"])
], remainder='passthrough')

# Pipeline
model = Pipeline([
    ("preprocessing", preprocessor),
    ("classifier", RandomForestClassifier())
])

# Train
model.fit(X, y)

# Save
pickle.dump(model, open("thyroid_01.pkl", "wb"))

